- name: Install Zabbix Repo
#  shell: yum install -y http://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-2.el7.noarch.rpm
  yum: name=http://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-2.el7.noarch.rpm state=installed

- name: Install Zabbix Agent
  yum: name=zabbix-agent state=installed

- name: Copy zabbix-agentd.conf
  template:
    src: templates/zabbix-agentd.conf.j2
    dest: /etc/zabbix/zabbix-agentd.conf
    owner: zabbix
    group: zabbix
    mode: '0644'

- name: Install semanage
  yum: name=policycoreutils-python state=installed

- name: Fix up SELinux
  shell: semanage permissive -a zabbix_agent_t

- name: Make sure zabbix-agent is started up and enabled
  service: name=zabbix-agent state=started enabled=yes

